image: maven:3-jdk-8
before_script:
  - 'source ./project.sh'
stages:
  - test
  - build
services:
  - 'mysql:5.5'
variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: muzix_db
  MYSQL_USER: test
  MYSQL_PASSWORD: test
  MYSQL_CI_URL: jdbc:mysql://mysql/muzix_db
cache:
 paths:
  - .m2/repository
  - target
maven-test:
  stage: test
  script: "mvn test"
maven-build:
  stage: build
  script: "mvn package"
  artifacts:
   paths:
    - 'target/*.jar'

